### ISSUE TITLE
https://www.politifact.com//api/v/2/statement/2635/?format=json is alread dead so to get the original text?

### ISSUE THREAD

**Issue by myrainbowandsky** [Tariq60/LIAR-PLUS#2]

**Comment by LittlePea13** [comment]
@myrainbowandsky did you find a way to get the jsons?

**Comment by Tariq60** [comment]
Politifact might have changed their api so could be the reason why these urls are not working now.

You could try reaching out to the author who released the original LIAR dataset (link in Readme), he might have a dump of the raw data
