### ISSUE TITLE
Wrong justifications in version 2 of the dataset (both tsv and jsonl)

### ISSUE THREAD

**Issue by rosafish** [Tariq60/LIAR-PLUS#4]
Hi, I was looking at your v2 datasets but figured some justifications were not working. For example, id 6890 has a justification that does not make sense, it also did not show up in the original PF article. I am switching to your v1 dataset, but thought it should be good to tell you.

**Comment by Tariq60** [comment]
I'll look into it.. Thanks for letting me know.
